[tool.poetry]
name = "sailowtech-ctd"
version = "0.1.0"
description = ""
authors = ["Arthur Jacobs <arthur.jacobs@sailowtech.ch>",
    "Mauro"]
readme = "README.md"
packages = [{ include = "sailowtech_ctd" }]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
